spring:
  application:
    name: rabbitMQ
  rabbitmq:
    host: 192.168.88.137
    port: 5672
    username: admin
    password: admin
server:
  port: 8765
info:
  app:
    name: RabbitMQ连接
    version: 0.0.1